### ISSUE TITLE
Handle html in meeting hooks

### ISSUE THREAD

**Issue by guillaumepotier** [Wisembly/Zapier#4]

**Comment by alexferr** [comment]
J'ai un user qui nous écrit ça : 
_I checked out the Zapier integration, but when it created a task in Asana for me it created it like this `<div>Creating a new asana task</div>` and it also leaves it unassigned. Any tips on how I can fix those problems?_

Comment c'est possible @guillaumepotier ? Ca pourrait venir de Zappier / Asana ?

**Comment by guillaumepotier** [comment]
C'est étrange qu'il ait du html. Je suis censé le sanitizer, je vais y jeter un oeil asap.
Pour le coup de c'est non assigné, il faut qu'il utilise le Zap "new action item assigned to you" et là il sera en mesure de se l'assigner dans Asana. Mais sinon ça arrive comme ça dans Asana et c'est là bas qu'il doit l'assigner, on sait pas mieux faire pour le moment.
